symfony/src/Entity/Infos.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\InfosRepository")
 */
class Infos
{

     /**
       * @var \User
       *
       * @ORM\Id
       * @ORM\GeneratedValue(strategy="NONE")
       * @ORM\OneToOne(targetEntity="User")
       * @ORM\JoinColumns({
       *   @ORM\JoinColumn(name="idMedecin", referencedColumnName="id")
       * })
       */
      private $idMedecin;

      /**
       * @ORM\Column(type="boolean", options={"default" : 0})
       */
      private $photo = 0;

      /**
       * @ORM\Column(type="string", length=255, nullable=true)
       */
      private $presentation;

      /**
       * @ORM\Column(type="string", length=255, nullable=true)
       */
      private $horaires;

      /**
       * @ORM\Column(type="integer", nullable=true)
       */
      private $tarif;

      /**
       * @ORM\Column(type="integer", nullable=true)
       */
      private $convention;

      /**
       * @ORM\Column(type="boolean", nullable=true)
       */
      private $carte_vitale;

      /**
       * @ORM\Column(type="boolean", nullable=true)
       */
      private $cb;

      /**
       * @ORM\Column(type="boolean", nullable=true)
       */
      private $cheque;

      /**
       * @ORM\Column(type="boolean", nullable=true)
       */
      private $espece;

      /**
       * @ORM\Column(type="string", length=50, nullable=true)
       */
      private $rue_cabinet;

      /**
       * @ORM\Column(type="string", length=50, nullable=true)
       */
      private $ville_cabinet;


      /**
       * @ORM\Column(type="integer", length=5, nullable=true)
       */
      private $code_postal;

      /**
       * @ORM\Column(type="string", length=50, nullable=true)
       */
      private $pays_cabinet;

      public function getIdMedecin(): ?int
      {
          return $this->idMedecin->getId();
      }

      public function setIdMedecin($idMedecin): self
      {
          $this->idMedecin = $idMedecin;

          return $this;
      }

      public function getPhoto(): ?bool
      {
          return $this->photo;
      }

      public function setPhoto(?bool $photo): self
      {
          $this->photo = $photo;

          return $this;
      }

      public function getPresentation(): ?string
      {
          return $this->presentation;
      }

      public function setPresentation(?string $presentation): self
      {
          $this->presentation = $presentation;

          return $this;
      }

      public function getHoraires(): ?string
      {
          return $this->horaires;
      }

      public function setHoraires(string $horaires): self
      {
          $this->horaires = $horaires;

          return $this;
      }

      public function getTarif(): ?int
      {
          return $this->tarif;
      }

      public function setTarif(int $tarif): self
      {
          $this->tarif = $tarif;

          return $this;
      }

      public function getConvention(): ?int
      {
          return $this->convention;
      }

      public function setConvention(int $convention): self
      {
          $this->convention = $convention;

          return $this;
      }

      public function getCarteVitale(): ?bool
      {
          return $this->carte_vitale;
      }

      public function setCarteVitale(bool $carte_vitale): self
      {
          $this->carte_vitale = $carte_vitale;

          return $this;
      }

      public function getCb(): ?bool
      {
          return $this->cb;
      }

      public function setCb(bool $cb): self
      {
          $this->cb = $cb;

          return $this;
      }

      public function getCheque(): ?bool
      {
          return $this->cheque;
      }

      public function setCheque(bool $cheque): self
      {
          $this->cheque = $cheque;

          return $this;
      }

      public function getEspece(): ?bool
      {
          return $this->espece;
      }

      public function setEspece(bool $espece): self
      {
          $this->espece = $espece;

          return $this;
      }

      public function getRueCabinet(): ?string
      {
          return $this->rue_cabinet;
      }

      public function setRueCabinet(string $rue_cabinet): self
      {
          $this->rue_cabinet = $rue_cabinet;

          return $this;
      }

      public function getVilleCabinet(): ?string
      {
          return $this->ville_cabinet;
      }

      public function setVilleCabinet(string $ville_cabinet): self
      {
          $this->ville_cabinet = $ville_cabinet;

          return $this;
      }

      public function getCodePostal(): ?int
      {
          return $this->code_postal;
      }

      public function setCodePostal(int $code_postal): self
      {
          $this->code_postal = $code_postal;

          return $this;
      }

      public function getPaysCabinet(): ?string
      {
          return $this->pays_cabinet;
      }

      public function setPaysCabinet(string $pays_cabinet): self
      {
          $this->pays_cabinet = $pays_cabinet;

          return $this;
      }
}

symfony/src/Entity/User.php
<?php
// src/Entity/User.php

namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="smallint")
     */
    private $genre;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $specialite;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $telephone;

   /**
    * @ORM\Column(type="string", length=100, nullable=true)
    */
   private $site_web;

   /**
    * @ORM\Column(type="string", length=100, nullable=true)
    */
   private $doctolib;

   /**
     * @ORM\OneToOne(targetEntity="Offre")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="offre", referencedColumnName="id")
     * })
    */
   private $offre;


    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    public function setEmail($email)
    {
        $email = is_null($email) ? '' : $email;
        parent::setEmail($email);
        $this->setUsername($email);

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getGenre(): ?int
    {
        return $this->genre;
    }

    public function setGenre(int $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->specialite;
    }

    public function setSpecialite(string $specialite): self
    {
        $this->specialite = $specialite;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getSiteWeb(): ?string
    {
        return $this->site_web;
    }

    public function setSiteWeb(?string $site_web): self
    {
        $this->site_web = $site_web;

        return $this;
    }

    public function getDoctolib(): ?string
    {
        return $this->doctolib;
    }

    public function setDoctolib(?string $doctolib): self
    {
        $this->doctolib = $doctolib;

        return $this;
    }

    public function getOffre()
    {
        return $this->offre;
    }

    public function setOffre($offre): self
    {
        $this->offre = $offre;

        return $this;
    }
}

symfony/src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Infos;
use FOS\UserBundle\Model\UserInterface;
use FOS\UserBundle\Model\UserManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ProfileController extends AbstractController
{
    /**
     * @Route("/profile", name="profile")
     */
    public function showUser()
    {
          $user = $this->getUser();

          $id = $user->getId();

          if (!is_object($user) || !$user instanceof UserInterface) {
              throw new AccessDeniedException('This user does not have access to this section.');
          }

          $infos = $this->getDoctrine()
              ->getRepository(Infos::class)
              ->find($id);

          return $this->render('@FOSUser/Profile/show.html.twig', array(
              'user' => $user, 'infos' => $infos,
          ));
    }
}

symfony/templates/bundles/FOSUserBundle/Profile/edit.html.twig
{% extends "@FOSUser/layout.html.twig" %}

{% block fos_user_content %}
{% include "@FOSUser/Profile/edit_content.html.twig" %}
{% endblock fos_user_content %}

symfony/templates/bundles/FOSUserBundle/Profile/edit_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

{{ form_start(form, { 'action': path('fos_user_profile_edit'), 'attr': { 'class': 'fos_user_profile_edit' } }) }}
    {{ form_widget(form) }}
    <div>
        <input type="submit" value="{{ 'profile.edit.submit'|trans }}" />
    </div>
{{ form_end(form) }}

symfony/templates/bundles/FOSUserBundle/Profile/show.html.twig
{% extends "@FOSUser/layout.html.twig" %}

{% block stylesheets %}
  <link rel="stylesheet" href="{{ asset('profile/css/style.css')}}" type="text/css">
{% endblock %}

{% block fos_user_content %}
{% include "@FOSUser/Profile/show_content.html.twig" %}
{% endblock fos_user_content %}

symfony/templates/bundles/FOSUserBundle/Profile/show_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

<section class="contenu">

  <div class="container-fluid py-4">
    <div class="row">

      <div class="mx-auto">
        <img
          src="

          {% if infos.photo != 0 %}
              {{ asset('dist/img/pp-medecin/' ~ user.nom ~ '_' ~ user.prenom ~ '.jpg')}}
          {% elseif user.genre == 0 %}
              {{ asset('dist/img/pp-medecin/default_dr_M.jpg')}}
          {% else %}
              {{ asset('dist/img/pp-medecin/default_dr_F.jpg')}}
          {% endif %}

          "
          alt="Photo de profil du {{ user.specialite }}, {{ user.nom }} {{ user.prenom }}">
      </div>

    </div>

    <div class="row pt-4">
      <h1 class="mx-auto">Dr. {{ user.nom }}</h1>
    </div>

    <div class="row">
      <h2 class="mx-auto">{{ user.specialite }}</h2>
    </div>

  </div>

  <div class="container pt-3 pb-5">

    <div class="row justify-content-center">
        <div class="col-12 col-md-6 btn-chat m-3">
         <a href="{{ path('configchatbot', {'id':user.id}) }}">
           <i class="fas fa-sliders-h"></i>Configurer mon Chatbot</a>
       </div>
    </div>

    <div class="row justify-content-center">

      <div class="jumbotron col-12 col-md-5 m-1">
        <h1>Présentation</h1>
        <p>{{ infos.presentation }}</p>
      </div>

      <div class="jumbotron col-12 col-md-5 m-1">
        <h1>Horaires</h1>
        <p>{{ infos.horaires }}</p>
      </div>

    </div>

    <div class="row justify-content-center">

      <div class="jumbotron col-12 col-md-5 m-1">
        <h1>Tarifs et remboursement</h1>
        <p>Consultation :
          {{ infos.tarif }}€</p>
        <p>Convention secteur
          {{ infos.convention }}</p>
        <p>Carte vitale :
          {% if infos.CarteVitale == 1 %}
            Acceptée
          {% else %}
            Rejetée
          {% endif %}
        </p>
      </div>

      <div class="jumbotron col-12 col-md-5 m-1">
        <h1>Moyen de paiement</h1>
        <p>
          <span class="badge
          {% if infos.cb == 1 %}
             badge-success">
          {% else %}
             badge-danger">
          {% endif %}
            Carte bleu</span>
        </p>
        <p>
          <span class="badge
          {% if infos.cheque == 1 %}
             badge-success">
          {% else %}
             badge-danger">
          {% endif %}
            Chèque</span>
        </p>
        <p>
          <span class="badge
          {% if infos.espece == 1 %}
             badge-success">
          {% else %}
             badge-danger">
          {% endif %}
            Espèce</span>
        </p>
      </div>

    </div>

    <div class="row justify-content-center">

      <div class="jumbotron col-12 col-md-5 m-1">
        <h1>Site web de votre médecin</h1>
        <a class="btn btn-primary" href="{{ user.siteWeb }}" role="button" target="_blank">
          <i class="fas fa-link"></i> Voir le site</a>
      </div>

      <div class="jumbotron col-12 col-md-5 m-1">
        <h1>Profil Doctolib</h1>
        <a class="btn btn-primary" href="{{ user.doctolib }}" role="button" target="_blank">
          <i class="fas fa-user-md"></i> Voir la page</a>
      </div>

    </div>

    <div class="row justify-content-center">

      <div class="jumbotron col-12 col-md-10 m-1">

        <h1>Localisation</h1>
        <p>{{ infos.rueCabinet }}<br>{{ infos.codePostal }}, {{ infos.villeCabinet }}</p>

        <div style="overflow:hidden;width: 100%;height: 440px;" class="mx-auto">
          <iframe
            width="100%"
            height="100%"
            src="https://maps.google.com/maps?width=700&amp;height=440&amp;hl=en&amp;q={{ infos.rueCabinet }}+{{ infos.villeCabinet }}+{{ infos.paysCabinet }}&amp;ie=UTF8&amp;t=&amp;z=13&amp;iwloc=B&amp;output=embed"
            frameborder="0"
            scrolling="no"
            marginheight="0"
            marginwidth="0">
          </iframe>
        </div>

        <div class="container text-center mt-3">
          <a href="{{ path('editInfos')}}">
            <button type="button" class="btn bg-sub primary-btn col-md-6 col-sm-6" name="button">Editer votre profil</button>
          </a>
        </div>

      </div>

    </div>

    <div class="col-12 col-md-6 btn-chat fixed-bottom mx-auto">
      <a href="{{ path('chatbot', {'id': user.id})}}">
        <i class="fas fa-comment-dots"></i> Parler au Dr. {{user.nom}}</a>
    </div>

  </section>